homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 108
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Customization file
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
  themes:
    happy:
      primary-color: pink
    sad:
      primary-color: blue
    darkred:
      # Main colors that can be changed
      dark-primary-color: "#c66900"
      disabled-text-color: "#545454"
      divider-color: "rgba(255, 255, 255, 0.12)"
      light-primary-color: "#e06c6c"
      paper-card-background-color: "#1d1d1d"
      paper-grey-200: "#191919"
      paper-item-icon-color: "#d3d3d3"
      paper-listbox-background-color: "#202020"
      primary-background-color: "#303030"
      primary-color: "#d32f2f"
      primary-text-color: "#cfcfcf"
      secondary-background-color: "#131313"
      sidebar-text_-_background: "#62717b" 
      # Colors based on variables, see above
      paper-card-header-color: "var(--paper-item-icon-color)" 
      paper-item-icon-active-color: "var(--primary-color)"
      paper-item-icon_-_color: "var(--primary-text-color)"
      paper-listbox-color: "var(--primary-text-color)"
      paper-grey-50: "var(--primary-text-color)"
      paper-slider-active-color: "var(--primary-color)"
      paper-slider-knob-color: "var(--primary-color)"
      paper-slider-knob-start-color: "var(--primary-color)"
      paper-slider-pin-color: "var(--primary-color)"
      paper-slider-secondary-color: "var(--light-primary-color)"
      paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-button-color: "var(--primary-color)"
      paper-toggle-button-checked-bar-color: "var(--light-primary-color)"
      paper-toggle-button-unchecked-bar-color: "var(--primary-text-color)"
      secondary-text-color: "var(--primary-color)"
      table-row-background-color: "var(--paper-card-background-color)"
      table-row-alternative-background-color: "var(--sidebar-text_-_background)"

config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_api_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# 1-15-17 the /hassio tab stopped showing up. I had to add this to get it back
hassio:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# The recorder component is storing details in a database which then are handled by the history component.
recorder:
  
# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

sensor: !include sensor.yaml
group: !include groups.yaml
switch: !include switches.yaml
light: !include light.yaml
automation: !include automations.yaml
script: !include scripts.yaml


# When HA starts to work with Smartthings, plug in your z-wave stick and uncomment the code below
# zwave:
#  usb_path: /dev/ttyACM0

blink:
  username: !secret blink_username
  password: !secret blink_password

# Enables the map componment
map:

# device_tracker:
#   - platform: automatic
#     client_id: !secret device_tracker_automatic_client_id
#     secret: !secret device_tracker_automatic_secret
#     current_location: true 

notify:
  - name: hassiopushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_token

mqtt:
  broker: core-mosquitto
  username: !secret mqtt_username
  password: !secret mqtt_password

plant:
  Lemon Tree:
    sensors:
      moisture: sensor.lemon_tree_moisture
      battery: sensor.lemon_tree_battery
      temperature: sensor.lemon_tree_temperature
      conductivity: sensor.lemon_tree_conductivity
      brightness: sensor.lemon_tree_light_intensity
    min_moisture: 20
    max_moisture: 30
    min_battery: 20
    min_temperature: 60

panel_custom:
  # - name: floorplan_example
  #   sidebar_title: Floorplan Example
  #   sidebar_icon: mdi:home
  #   url_path: floorplan
  #   config: !include floorplan-example.yaml
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

emulated_hue:
  host_ip: !secret emulated_hue_host_ip
  listen_port: 8300
  expose_by_default: false
  # You have to explicitly make things accessable to the emulated hue in the customize.yaml file
  # you can check what Alexa can see here: http://hassio.local:8300/api/pi/lights
  # Full documentation here: https://home-assistant.io/components/emulated_hue/

# Full configuration.yaml entry
history_graph:
  gr1:
    name: Lemon stats
    entities:
      - switch.lemon_lights
      - sensor.lemon_tree_moisture
      - switch.sonoff3
      - sensor.lemon_tree_temperature
      - sensor.lemon_tree_light_intensity
    hours_to_show: 240
    #refresh: 60
  gr2:
    name: Temperature
    entities:
      - sensor.bedroom_window_temperature
      - sensor.office_window_temperature
      - sensor.blink_garage_temperature
      - sensor.door_sensor_backdoor_slider__temperature
      - sensor.front_door_temperature
      - sensor.garage_temp__temperature
      - sensor.weather_temperature
      - sensor.lemon_tree_temperature
    hours_to_show: 240

skybell:
  username: !secret skybell_username
  password: !secret skybell_password
camera:
  - platform: skybell
  # This is the camera connected to the octoprint
  - platform: mjpeg
    mjpeg_url: http://192.168.86.150/webcam/?action=stream
    still_image_url: http://192.168.86.150/webcam/?action=snapshot
binary_sensor:
  - platform: skybell
    monitored_conditions:
      - button
      - motion
  - platform: octoprint
    monitored_conditions:
      - Printing
      - Printing Error

input_boolean:
  notify_home:
    name: Bool for Notify when the first person arrives home - used in Jason arrives automation
    initial: off
  welcome_home_announcement:
    name: Welcome home Neff or Nichol Boolean
    initial: off
  jasons_workout_bool:
    name: Jason is probably working out Boolean
    initial: off
  mails_here_bool:
    name: Mail is here Boolean
    initial: off

octoprint:
  host: !secret octoprint_host
  api_key: !secret octoprint_api
  bed: true
  number_of_tools: 1

 
